#!/bin/sh

set -e
exec 2>&1

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
APP_USER="${CONTAINER_USER:-vscode}"

/usr/bin/install -d -o "${APP_USER}" -g "${APP_USER}" -m 0755 /var/log/app
exec /sbin/su-exec "${APP_USER}" /usr/local/bin/start-service.sh
